//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALShopThoiTrang.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        public string maNV { get; set; }
        public string tenNV { get; set; }
        public string soDienThoai { get; set; }
        public string chucVu { get; set; }
        public string trangThai { get; set; }
        public string matKhau { get; set; }
        public string phanQuyen { get; set; }
        public string gioiTinh { get; set; }
    }
}
